services:
  - docker

script:
  - docker run
    -v $(pwd):/repo
    -e PROJECT=release-manager
    -e BRANCH=$TRAVIS_BRANCH
    -e COMMIT_ID=$TRAVIS_COMMIT
    -e IS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    -e AWS_ACCESS_KEY_ID
    -e AWS_SECRET_ACCESS_KEY
    -e ENC_PASS_AWS
    hollowverse/build-env

notifications:
  email: false

